// lang.js - Полная языковая поддержка для Chain Bank (Orthodox)
const translations = {
    en: {
        // Основные
        title: "Chain Bank",
        motto: "Orthodox · Faith in Blockchain",
        candles: "Candles",
        buy_tokens: "Buy tokens",
        dao: "DAO",
        memory: "Memory",
        prayers: "Prayers",
        saints: "Saints",
        pilgrim: "Pilgrim",
        parishes: "Parishes",
        back: "← Back",

        // Блок пользователя
        yourWallet: "Your data for recording",
        wallet_placeholder: "Your Solana wallet",
        name_placeholder: "Your name",
        save: "✙ Save",
        saved: "Saved",
        copied: "Copied!",
        need_wallet: "Enter wallet",
        need_txid: "Enter TXID",

        // Кнопки действий с токенами
        forGod: "For God",
        againstGod: "Against God",
        for_btn: "📿 For God",
        against_btn: "💀 Against God",
        eternal_btn: "✨ Eternal Candle",
        send_vbdc_desc: "Send 1 USVT to BOG address. Paste TXID:",
        send_deus_desc: "Send 1 BOG to DEMON address. Paste TXID:",
        send_eternal_desc: "Send 1 USVT + 1 DEMON to BOG address. Paste TXID:",

        // Модальное окно верификации
        verify_title: "Confirmation",
        txid_placeholder: "Paste TXID (transaction hash)",
        verify_btn: "✙ Verify",

        // Благотворительность и пожертвования
        donate_direct: "Direct donations (SOL / USDC)",
        copy: "📋 Copy",
        swap_title: "Buy tokens via swap",
        onramp_title: "Buy SOL/USDC with card",
        swift_title: "Large donations (SWIFT / SEPA)",
        swift_desc: "For donations from $1000. After transfer, contact us:",
        swift_note: "📌 After transfer, send confirmation and your wallet — we will credit tokens manually.",
        refer_title: "Refer a friend",
        footer: "Faith, hope, love and blockchain",

        // Главная страница (виджеты)
        calendar: "📅 Liturgical Calendar",
        live_mass: "📺 Live from Orthodox Church",
        top_donors: "👑 Top Donors (this week)",
        burning_candles: "🔥 Burning Candles",

        // Общие сообщения
        no_donors: "No donors yet. Be the first!",
        no_candles: "🙏 No candles yet. Light the first one!",
        no_entries: "No entries yet",
        no_proposals: "No active proposals",
        no_votes: "No votes yet",
        already_voted: "Already voted",
        enter_wallet: "Enter wallet",
        candle_lit: "✅ Candle lit!",
        verified: "✅ Verified!",
        error: "❌ Error"
    },
    ru: {
        title: "Chain Bank",
        motto: "Православие · Вера в блокчейне",
        candles: "Свечи",
        buy_tokens: "Купить токены",
        dao: "DAO",
        memory: "Книга памяти",
        prayers: "Молитвы",
        saints: "Святые",
        pilgrim: "Паломник",
        parishes: "Храмы",
        back: "← На главную",

        yourWallet: "Ваши данные для записи",
        wallet_placeholder: "Ваш Solana кошелёк",
        name_placeholder: "Ваше имя",
        save: "✙ Сохранить",
        saved: "Сохранено",
        copied: "Скопировано!",
        need_wallet: "Введите кошелёк",
        need_txid: "Введите TXID",

        forGod: "За Бога",
        againstGod: "Против Бога",
        for_btn: "📿 За Бога",
        against_btn: "💀 Против Бога",
        eternal_btn: "✨ Вечная свеча",
        send_vbdc_desc: "Отправьте 1 USVT на адрес BOG. Вставьте TXID:",
        send_deus_desc: "Отправьте 1 BOG на адрес DEMON. Вставьте TXID:",
        send_eternal_desc: "Отправьте 1 USVT + 1 DEMON на адрес BOG. Вставьте TXID:",

        verify_title: "Подтверждение",
        txid_placeholder: "Вставьте TXID (хеш транзакции)",
        verify_btn: "✙ Проверить",

        donate_direct: "Прямые пожертвования (SOL / USDC)",
        copy: "📋 Копировать",
        swap_title: "Купить токены через своп",
        onramp_title: "Купить SOL/USDC с карты",
        swift_title: "Крупные пожертвования (SWIFT / SEPA)",
        swift_desc: "Для пожертвований от $1000. После перевода свяжитесь с нами:",
        swift_note: "📌 После перевода отправьте подтверждение и ваш кошелёк — мы зачислим токены вручную.",
        refer_title: "Приведи друга",
        footer: "Вера, надежда, любовь и блокчейн",

        calendar: "📅 Литургический календарь",
        live_mass: "📺 Прямая трансляция из храма",
        top_donors: "👑 Топ доноров (неделя)",
        burning_candles: "🔥 Горящие свечи",

        no_donors: "Пока никого. Станьте первым!",
        no_candles: "🙏 Пока нет свечей. Зажгите первую!",
        no_entries: "Пока нет записей",
        no_proposals: "Нет активных голосований",
        no_votes: "Вы ещё не голосовали",
        already_voted: "Вы уже голосовали",
        enter_wallet: "Введите кошелёк",
        candle_lit: "✅ Свеча зажжена!",
        verified: "✅ Проверено!",
        error: "❌ Ошибка"
    },
    es: {
        title: "Chain Bank",
        motto: "Ortodoxo · Fe en Blockchain",
        candles: "Velas",
        buy_tokens: "Comprar tokens",
        dao: "DAO",
        memory: "Memoria",
        prayers: "Oraciones",
        saints: "Santos",
        pilgrim: "Peregrino",
        parishes: "Parroquias",
        back: "← Volver",
        yourWallet: "Tus datos",
        wallet_placeholder: "Tu billetera Solana",
        name_placeholder: "Tu nombre",
        save: "✙ Guardar",
        saved: "Guardado",
        copied: "¡Copiado!",
        need_wallet: "Ingrese billetera",
        need_txid: "Ingrese TXID",
        forGod: "Para Dios",
        againstGod: "Contra Dios",
        for_btn: "📿 Para Dios",
        against_btn: "💀 Contra Dios",
        eternal_btn: "✨ Vela eterna",
        send_vbdc_desc: "Envía 1 USVT a la dirección BOG. Pegue TXID:",
        send_deus_desc: "Envía 1 BOG a la dirección DEMON. Pegue TXID:",
        send_eternal_desc: "Envía 1 USVT + 1 DEMON a la dirección BOG. Pegue TXID:",
        verify_title: "Confirmación",
        txid_placeholder: "Pegue TXID",
        verify_btn: "✙ Verificar",
        donate_direct: "Donaciones directas (SOL/USDC)",
        copy: "📋 Copiar",
        swap_title: "Comprar tokens mediante swap",
        onramp_title: "Comprar SOL/USDC con tarjeta",
        swift_title: "Grandes donaciones (SWIFT/SEPA)",
        swift_desc: "Para donaciones desde $1000. Después de transferir, contáctenos:",
        swift_note: "📌 Envíe confirmación y su billetera — acreditaremos tokens manualmente.",
        refer_title: "Recomendar amigo",
        footer: "Fe, esperanza, amor y blockchain",
        calendar: "📅 Calendario litúrgico",
        live_mass: "📺 En vivo desde iglesia ortodoxa",
        top_donors: "👑 Mejores donantes (esta semana)",
        burning_candles: "🔥 Velas encendidas",
        no_donors: "Aún no hay donantes. ¡Sé el primero!",
        no_candles: "🙏 Aún no hay velas. ¡Enciende la primera!",
        no_entries: "Aún no hay entradas",
        no_proposals: "No hay propuestas activas",
        no_votes: "Aún no has votado",
        already_voted: "Ya has votado",
        enter_wallet: "Ingrese billetera",
        candle_lit: "✅ ¡Vela encendida!",
        verified: "✅ ¡Verificado!",
        error: "❌ Error"
    },
    zh: {
        title: "Chain Bank",
        motto: "东正教 · 区块链中的信仰",
        candles: "蜡烛",
        buy_tokens: "购买代币",
        dao: "DAO",
        memory: "记忆",
        prayers: "祈祷",
        saints: "圣徒",
        pilgrim: "朝圣者",
        parishes: "教区",
        back: "← 返回",
        yourWallet: "您的数据",
        wallet_placeholder: "您的Solana钱包",
        name_placeholder: "您的名字",
        save: "✙ 保存",
        saved: "已保存",
        copied: "已复制！",
        need_wallet: "输入钱包",
        need_txid: "输入TXID",
        forGod: "为了上帝",
        againstGod: "对抗上帝",
        for_btn: "📿 为了上帝",
        against_btn: "💀 对抗上帝",
        eternal_btn: "✨ 永恒蜡烛",
        send_vbdc_desc: "发送1 USVT到BOG地址。粘贴TXID：",
        send_deus_desc: "发送1 BOG到DEMON地址。粘贴TXID：",
        send_eternal_desc: "发送1 USVT + 1 DEMON到BOG地址。粘贴TXID：",
        verify_title: "确认",
        txid_placeholder: "粘贴TXID",
        verify_btn: "✙ 验证",
        donate_direct: "直接捐赠 (SOL/USDC)",
        copy: "📋 复制",
        swap_title: "通过交换购买代币",
        onramp_title: "用卡购买SOL/USDC",
        swift_title: "大额捐赠 (SWIFT/SEPA)",
        swift_desc: "捐赠$1000起。转账后联系我们：",
        swift_note: "📌 转账后发送确认信息和您的钱包——我们将手动记入代币。",
        refer_title: "推荐朋友",
        footer: "信仰、希望、爱与区块链",
        calendar: "📅 礼拜日历",
        live_mass: "📺 东正教教堂直播",
        top_donors: "👑 顶级捐赠者（本周）",
        burning_candles: "🔥 燃烧的蜡烛",
        no_donors: "暂无捐赠者。成为第一个！",
        no_candles: "🙏 暂无蜡烛。点燃第一支！",
        no_entries: "暂无记录",
        no_proposals: "暂无活跃提案",
        no_votes: "您尚未投票",
        already_voted: "您已投票",
        enter_wallet: "输入钱包",
        candle_lit: "✅ 蜡烛已点燃！",
        verified: "✅ 已验证！",
        error: "❌ 错误"
    },
    fr: {
        title: "Chain Bank",
        motto: "Orthodoxe · Foi dans la Blockchain",
        candles: "Bougies",
        buy_tokens: "Acheter des tokens",
        dao: "DAO",
        memory: "Mémoire",
        prayers: "Prières",
        saints: "Saints",
        pilgrim: "Pèlerin",
        parishes: "Paroisses",
        back: "← Retour",
        yourWallet: "Vos données",
        wallet_placeholder: "Votre portefeuille Solana",
        name_placeholder: "Votre nom",
        save: "✙ Sauvegarder",
        saved: "Sauvegardé",
        copied: "Copié !",
        need_wallet: "Entrez le portefeuille",
        need_txid: "Entrez TXID",
        forGod: "Pour Dieu",
        againstGod: "Contre Dieu",
        for_btn: "📿 Pour Dieu",
        against_btn: "💀 Contre Dieu",
        eternal_btn: "✨ Bougie éternelle",
        send_vbdc_desc: "Envoyez 1 USVT à l'adresse BOG. Collez TXID :",
        send_deus_desc: "Envoyez 1 BOG à l'adresse DEMON. Collez TXID :",
        send_eternal_desc: "Envoyez 1 USVT + 1 DEMON à l'adresse BOG. Collez TXID :",
        verify_title: "Confirmation",
        txid_placeholder: "Collez TXID",
        verify_btn: "✙ Vérifier",
        donate_direct: "Dons directs (SOL/USDC)",
        copy: "📋 Copier",
        swap_title: "Acheter des tokens via swap",
        onramp_title: "Acheter SOL/USDC par carte",
        swift_title: "Dons importants (SWIFT/SEPA)",
        swift_desc: "Pour les dons à partir de $1000. Après le transfert, contactez-nous :",
        swift_note: "📌 Après le transfert, envoyez la confirmation et votre portefeuille — nous créditerons les tokens manuellement.",
        refer_title: "Parrainer un ami",
        footer: "Foi, espérance, amour et blockchain",
        calendar: "📅 Calendrier liturgique",
        live_mass: "📺 En direct de l'église orthodoxe",
        top_donors: "👑 Meilleurs donateurs (cette semaine)",
        burning_candles: "🔥 Bougies allumées",
        no_donors: "Pas encore de donateurs. Soyez le premier !",
        no_candles: "🙏 Pas encore de bougies. Allumez la première !",
        no_entries: "Pas encore d'entrées",
        no_proposals: "Pas de propositions actives",
        no_votes: "Vous n'avez pas encore voté",
        already_voted: "Vous avez déjà voté",
        enter_wallet: "Entrez le portefeuille",
        candle_lit: "✅ Bougie allumée !",
        verified: "✅ Vérifié !",
        error: "❌ Erreur"
    },
    de: {
        title: "Chain Bank",
        motto: "Orthodox · Glaube in Blockchain",
        candles: "Kerzen",
        buy_tokens: "Token kaufen",
        dao: "DAO",
        memory: "Gedenken",
        prayers: "Gebete",
        saints: "Heilige",
        pilgrim: "Pilger",
        parishes: "Gemeinden",
        back: "← Zurück",
        yourWallet: "Ihre Daten",
        wallet_placeholder: "Ihre Solana Wallet",
        name_placeholder: "Ihr Name",
        save: "✙ Speichern",
        saved: "Gespeichert",
        copied: "Kopiert!",
        need_wallet: "Wallet eingeben",
        need_txid: "TXID eingeben",
        forGod: "Für Gott",
        againstGod: "Gegen Gott",
        for_btn: "📿 Für Gott",
        against_btn: "💀 Gegen Gott",
        eternal_btn: "✨ Ewige Kerze",
        send_vbdc_desc: "Senden Sie 1 USVT an die BOG-Adresse. Fügen Sie TXID ein:",
        send_deus_desc: "Senden Sie 1 BOG an die DEMON-Adresse. Fügen Sie TXID ein:",
        send_eternal_desc: "Senden Sie 1 USVT + 1 DEMON an die BOG-Adresse. Fügen Sie TXID ein:",
        verify_title: "Bestätigung",
        txid_placeholder: "TXID einfügen",
        verify_btn: "✙ Prüfen",
        donate_direct: "Direkte Spenden (SOL/USDC)",
        copy: "📋 Kopieren",
        swap_title: "Token per Swap kaufen",
        onramp_title: "SOL/USDC mit Karte kaufen",
        swift_title: "Großspenden (SWIFT/SEPA)",
        swift_desc: "Für Spenden ab $1000. Nach der Überweisung kontaktieren Sie uns:",
        swift_note: "📌 Senden Sie die Bestätigung und Ihre Wallet — wir werden die Token manuell gutschreiben.",
        refer_title: "Freund empfehlen",
        footer: "Glaube, Hoffnung, Liebe und Blockchain",
        calendar: "📅 Liturgischer Kalender",
        live_mass: "📺 Live aus der orthodoxen Kirche",
        top_donors: "👑 Top-Spender (diese Woche)",
        burning_candles: "🔥 Brennende Kerzen",
        no_donors: "Noch keine Spender. Seien Sie der Erste!",
        no_candles: "🙏 Noch keine Kerzen. Zünden Sie die erste an!",
        no_entries: "Noch keine Einträge",
        no_proposals: "Keine aktiven Vorschläge",
        no_votes: "Sie haben noch nicht abgestimmt",
        already_voted: "Sie haben bereits abgestimmt",
        enter_wallet: "Wallet eingeben",
        candle_lit: "✅ Kerze angezündet!",
        verified: "✅ Verifiziert!",
        error: "❌ Fehler"
    },
    it: {
        title: "Chain Bank",
        motto: "Ortodosso · Fede nella Blockchain",
        candles: "Candele",
        buy_tokens: "Compra token",
        dao: "DAO",
        memory: "Memoria",
        prayers: "Preghiere",
        saints: "Santi",
        pilgrim: "Pellegrino",
        parishes: "Parrocchie",
        back: "← Indietro",
        yourWallet: "I tuoi dati",
        wallet_placeholder: "Il tuo portafoglio Solana",
        name_placeholder: "Il tuo nome",
        save: "✙ Salva",
        saved: "Salvato",
        copied: "Copiato!",
        need_wallet: "Inserisci portafoglio",
        need_txid: "Inserisci TXID",
        forGod: "Per Dio",
        againstGod: "Contro Dio",
        for_btn: "📿 Per Dio",
        against_btn: "💀 Contro Dio",
        eternal_btn: "✨ Candela eterna",
        send_vbdc_desc: "Invia 1 USVT all'indirizzo BOG. Incolla TXID:",
        send_deus_desc: "Invia 1 BOG all'indirizzo DEMON. Incolla TXID:",
        send_eternal_desc: "Invia 1 USVT + 1 DEMON all'indirizzo BOG. Incolla TXID:",
        verify_title: "Conferma",
        txid_placeholder: "Incolla TXID",
        verify_btn: "✙ Verifica",
        donate_direct: "Donazioni dirette (SOL/USDC)",
        copy: "📋 Copia",
        swap_title: "Compra token tramite swap",
        onramp_title: "Compra SOL/USDC con carta",
        swift_title: "Grandi donazioni (SWIFT/SEPA)",
        swift_desc: "Per donazioni da $1000. Dopo il trasferimento, contattaci:",
        swift_note: "📌 Dopo il trasferimento, invia conferma e il tuo portafoglio — accrediteremo i token manualmente.",
        refer_title: "Invita un amico",
        footer: "Fede, speranza, amore e blockchain",
        calendar: "📅 Calendario liturgico",
        live_mass: "📺 Diretta dalla chiesa ortodossa",
        top_donors: "👑 Migliori donatori (questa settimana)",
        burning_candles: "🔥 Candele accese",
        no_donors: "Ancora nessun donatore. Sii il primo!",
        no_candles: "🙏 Ancora nessuna candela. Accendi la prima!",
        no_entries: "Ancora nessuna voce",
        no_proposals: "Nessuna proposta attiva",
        no_votes: "Non hai ancora votato",
        already_voted: "Hai già votato",
        enter_wallet: "Inserisci portafoglio",
        candle_lit: "✅ Candela accesa!",
        verified: "✅ Verificato!",
        error: "❌ Errore"
    },
    ja: {
        title: "Chain Bank",
        motto: "正教 · ブロックチェーンにおける信仰",
        candles: "キャンドル",
        buy_tokens: "トークンを購入",
        dao: "DAO",
        memory: "追悼",
        prayers: "祈り",
        saints: "聖人",
        pilgrim: "巡礼者",
        parishes: "教区",
        back: "← 戻る",
        yourWallet: "あなたのデータ",
        wallet_placeholder: "あなたのSolanaウォレット",
        name_placeholder: "あなたの名前",
        save: "✙ 保存",
        saved: "保存しました",
        copied: "コピーしました！",
        need_wallet: "ウォレットを入力",
        need_txid: "TXIDを入力",
        forGod: "神のために",
        againstGod: "神に逆らう",
        for_btn: "📿 神のために",
        against_btn: "💀 神に逆らう",
        eternal_btn: "✨ 永遠のキャンドル",
        send_vbdc_desc: "1 USVTをBOGアドレスに送信します。TXIDを貼り付けてください：",
        send_deus_desc: "1 BOGをDEMONアドレスに送信します。TXIDを貼り付けてください：",
        send_eternal_desc: "1 USVT + 1 DEMONをBOGアドレスに送信します。TXIDを貼り付けてください：",
        verify_title: "確認",
        txid_placeholder: "TXIDを貼り付け",
        verify_btn: "✙ 検証",
        donate_direct: "直接寄付 (SOL/USDC)",
        copy: "📋 コピー",
        swap_title: "スワップでトークンを購入",
        onramp_title: "カードでSOL/USDCを購入",
        swift_title: "大口寄付 (SWIFT/SEPA)",
        swift_desc: "$1000以上の寄付の場合。送金後、お問い合わせください：",
        swift_note: "📌 送金後、確認とウォレットを送信してください — 手動でトークンを記入します。",
        refer_title: "友人を紹介",
        footer: "信仰、希望、愛、そしてブロックチェーン",
        calendar: "📅 典礼カレンダー",
        live_mass: "📺 正教会からのライブ",
        top_donors: "👑 トップドナー（今週）",
        burning_candles: "🔥 燃えているキャンドル",
        no_donors: "まだドナーはいません。最初になりましょう！",
        no_candles: "🙏 まだキャンドルはありません。最初に灯してください！",
        no_entries: "まだエントリーはありません",
        no_proposals: "アクティブな提案はありません",
        no_votes: "まだ投票していません",
        already_voted: "すでに投票済みです",
        enter_wallet: "ウォレットを入力してください",
        candle_lit: "✅ キャンドルが灯されました！",
        verified: "✅ 検証済み！",
        error: "❌ エラー"
    }
};

let currentLang = localStorage.getItem('chainbank_lang') || 'ru';

function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('chainbank_lang', lang);
    
    // Переводим элементы с data-i18n
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                el.placeholder = translations[lang][key];
            } else {
                el.innerHTML = translations[lang][key];
            }
        }
    });
    
    // Переводим плейсхолдеры с data-i18n-placeholder
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[lang] && translations[lang][key]) {
            el.placeholder = translations[lang][key];
        }
    });
    
    // Обновляем активный класс для кнопок языка
    document.querySelectorAll('.lang-btn').forEach(btn => {
        if (btn.dataset.lang === lang) {
            btn.classList.add('active');
        } else {
            btn.classList.remove('active');
        }
    });
}

function renderLangButtons(containerId = 'lang-switcher') {
    const container = document.getElementById(containerId);
    if (!container) return;
    
    const langs = { en:'EN', ru:'RU', es:'ES', zh:'中文', fr:'FR', de:'DE', it:'IT', ja:'JP' };
    container.innerHTML = '';
    
    Object.entries(langs).forEach(([code, name]) => {
        const btn = document.createElement('button');
        btn.innerText = name;
        btn.dataset.lang = code;
        btn.className = `lang-btn ${currentLang === code ? 'active' : ''} bg-white/10 hover:bg-gold/30 px-2 py-1 rounded-full text-sm transition`;
        btn.onclick = () => setLanguage(code);
        container.appendChild(btn);
    });
}

// Автоматическая инициализация при загрузке страницы
document.addEventListener('DOMContentLoaded', () => {
    renderLangButtons();
    setLanguage(currentLang);
});

// Делаем функции и переводы глобальными для доступа из других скриптов
window.translations = translations;
window.currentLang = currentLang;
window.setLanguage = setLanguage;
window.renderLangButtons = renderLangButtons;
