// Для русского (ru)
deed1: "Обычная свеча", deed1_desc: "Отправьте 1 USVT на адрес Бога",
deed2: "Вечная свеча", deed2_desc: "Отправьте 1 USVT + 1 DEMON на адрес Бога",
deed3: "Соборная свеча", deed3_desc: "Отправьте 10 USVT на адрес Бога",
deed4: "Именная молитва", deed4_desc: "Отправьте 5 USVT на адрес Бога",
deed5: "Сорокоуст (40 дней)", deed5_desc: "Отправьте 40 USVT на адрес Бога",
deed6: "Годовая свеча", deed6_desc: "Отправьте 365 USVT на адрес Бога",
deed7: "Поминовение в храме", deed7_desc: "Отправьте 100 USVT на адрес Бога",
deed8: "Молитвенное правило", deed8_desc: "Отправьте 1 USVT на адрес Бога",
deed9: "Аватар святого", deed9_desc: "Отправьте 50 USVT на адрес Бога",
deed10: "Икона в галерее", deed10_desc: "Отправьте 100 USVT на адрес Бога",
deed11: "Молебен онлайн", deed11_desc: "Отправьте 20 USVT на адрес Бога",
deed12: "Пожертвование", deed12_desc: "Отправьте любую сумму USVT на адрес Бога",
deed13: "Друг монастыря", deed13_desc: "Отправьте 50 USVT (месяц) на адрес Бога",
deed14: "Создать голосование", deed14_desc: "Отправьте 100 BOG на адрес DEMON",
deed15: "Усилить голос", deed15_desc: "Отправьте 1000 BOG на адрес DEMON",
deed16: "Старейшина", deed16_desc: "Отправьте 500 USVT на адрес Бога",
deed17: "Реклама на сайте", deed17_desc: "Отправьте 200 USVT на адрес Бога",
deed18: "NFT-икона", deed18_desc: "Отправьте 50 USVT на адрес Бога",
deed19: "Фрагмент мощей", deed19_desc: "Отправьте 500 USVT на адрес Бога",
deed20: "12 апостолов", deed20_desc: "Отправьте 600 USVT на адрес Бога",
deed21: "Сертификат паломника", deed21_desc: "Отправьте 30 USVT на адрес Бога",
deed22: "Осквернить свечу", deed22_desc: "Отправьте 1 DEMON на адрес Бога",
deed23: "Чёрная свеча", deed23_desc: "Отправьте 1 DEMON на адрес Бога",
deed24: "Богохульник недели", deed24_desc: "Отправьте 100 DEMON на адрес Бога",
deed25: "Снять икону", deed25_desc: "Отправьте 50 DEMON на адрес Бога",
deed26: "За любимого человека", deed26_desc: "Отправьте 1 USVT на адрес Бога",
deed27: "За здоровье близкого", deed27_desc: "Отправьте 3 USVT на адрес Бога",
deed28: "За удачу в делах", deed28_desc: "Отправьте 5 USVT на адрес Бога",
deed29: "За путешествующих", deed29_desc: "Отправьте 2 USVT на адрес Бога",
deed30: "За благополучие семьи", deed30_desc: "Отправьте 10 USVT на адрес Бога",
deed31: "За усопших", deed31_desc: "Отправьте 1 USVT на адрес Бога",
deed32: "За здравие своё", deed32_desc: "Отправьте 2 USVT на адрес Бога",
deed33: "За прощение грехов", deed33_desc: "Отправьте 7 USVT на адрес Бога",
deed34: "За укрепление веры", deed34_desc: "Отправьте 5 USVT на адрес Бога",
deed35: "За избавление от уныния", deed35_desc: "Отправьте 3 USVT на адрес Бога",
deed36: "За всех православных", deed36_desc: "Отправьте 1 USVT на адрес Бога",
deed37: "За мир во всём мире", deed37_desc: "Отправьте 10 USVT на адрес Бога",
deed38: "За болящих и страждущих", deed38_desc: "Отправьте 5 USVT на адрес Бога",
deed39: "За обиженных и угнетённых", deed39_desc: "Отправьте 3 USVT на адрес Бога",
deed40: "За всех усопших безродных", deed40_desc: "Отправьте 2 USVT на адрес Бога",

// Для английского (en)
deed1: "🕯️ Ordinary Candle", deed1_desc: "Send 1 USVT to God's address",
deed2: "✨ Eternal Candle", deed2_desc: "Send 1 USVT + 1 DEMON to God's address",
deed3: "🏛️ Cathedral Candle", deed3_desc: "Send 10 USVT to God's address",
deed4: "📿 Named Prayer", deed4_desc: "Send 5 USVT to God's address",
deed5: "📆 Sorokoust (40 days)", deed5_desc: "Send 40 USVT to God's address",
deed6: "📅 Yearly Candle", deed6_desc: "Send 365 USVT to God's address",
deed7: "⛪ Church Memorial", deed7_desc: "Send 100 USVT to God's address",
deed8: "📖 Prayer Rule", deed8_desc: "Send 1 USVT to God's address",
deed9: "🎨 Saint Avatar", deed9_desc: "Send 50 USVT to God's address",
deed10: "🖼️ Icon in Gallery", deed10_desc: "Send 100 USVT to God's address",
deed11: "🙏 Online Moleben", deed11_desc: "Send 20 USVT to God's address",
deed12: "🤝 Donation", deed12_desc: "Send any amount of USVT to God's address",
deed13: "🏅 Friend of Monastery", deed13_desc: "Send 50 USVT (month) to God's address",
deed14: "🗳️ Create Vote", deed14_desc: "Send 100 BOG to DEMON address",
deed15: "⚡ Strengthen Vote", deed15_desc: "Send 1000 BOG to DEMON address",
deed16: "👑 Elder", deed16_desc: "Send 500 USVT to God's address",
deed17: "📢 Site Advertising", deed17_desc: "Send 200 USVT to God's address",
deed18: "🖼️ NFT Icon", deed18_desc: "Send 50 USVT to God's address",
deed19: "🕊️ Relic Fragment", deed19_desc: "Send 500 USVT to God's address",
deed20: "👥 12 Apostles", deed20_desc: "Send 600 USVT to God's address",
deed21: "🎓 Pilgrim Certificate", deed21_desc: "Send 30 USVT to God's address",
deed22: "💀 Desecrate Candle", deed22_desc: "Send 1 DEMON to God's address",
deed23: "⚫ Black Candle", deed23_desc: "Send 1 DEMON to God's address",
deed24: "👿 Blasphemer of the Week", deed24_desc: "Send 100 DEMON to God's address",
deed25: "🗑️ Remove Icon", deed25_desc: "Send 50 DEMON to God's address",
deed26: "🙏 For a Loved One", deed26_desc: "Send 1 USVT to God's address",
deed27: "🕯️ For Health of a Relative", deed27_desc: "Send 3 USVT to God's address",
deed28: "🍀 For Luck in Business", deed28_desc: "Send 5 USVT to God's address",
deed29: "✈️ For Travelers", deed29_desc: "Send 2 USVT to God's address",
deed30: "🏠 For Family Well-being", deed30_desc: "Send 10 USVT to God's address",
deed31: "⚰️ For the Departed", deed31_desc: "Send 1 USVT to God's address",
deed32: "💪 For Your Own Health", deed32_desc: "Send 2 USVT to God's address",
deed33: "🙌 For Forgiveness of Sins", deed33_desc: "Send 7 USVT to God's address",
deed34: "⛪ For Strengthening Faith", deed34_desc: "Send 5 USVT to God's address",
deed35: "😌 For Deliverance from Despondency", deed35_desc: "Send 3 USVT to God's address",
deed36: "🌍 For All Orthodox", deed36_desc: "Send 1 USVT to God's address",
deed37: "🕊️ For World Peace", deed37_desc: "Send 10 USVT to God's address",
deed38: "🤒 For the Sick and Suffering", deed38_desc: "Send 5 USVT to God's address",
deed39: "🛡️ For the Oppressed", deed39_desc: "Send 3 USVT to God's address",
deed40: "🕯️ For All Forgotten Departed", deed40_desc: "Send 2 USVT to God's address",
